spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: none
    database: postgresql
server:
  error:
    includeMessage: ALWAYS
    includeStacktrace: NEVER
    includeBindingErrors: NEVER
management.endpoints.web.base-path: /rest/v1/
springdoc.api-docs.path: /rest/v1/api-docs
springdoc.swagger-ui.path: /swagger-ui.html
logging.level.com.musala.artemis.dronemanager: INFO
